# coding: utf-8

"""
    Personal Finance Tracker

    Personal Finance Tracker API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finance_sdk.models.batch_reclassify_request import BatchReclassifyRequest

class TestBatchReclassifyRequest(unittest.TestCase):
    """BatchReclassifyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchReclassifyRequest:
        """Test BatchReclassifyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchReclassifyRequest`
        """
        model = BatchReclassifyRequest()
        if include_optional:
            return BatchReclassifyRequest(
                filter = {
                    'key' : ''
                    },
                new_category = ''
            )
        else:
            return BatchReclassifyRequest(
                filter = {
                    'key' : ''
                    },
                new_category = '',
        )
        """

    def testBatchReclassifyRequest(self):
        """Test BatchReclassifyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
