# coding: utf-8

"""
    Personal Finance Tracker

    Personal Finance Tracker API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finance_sdk.models.transaction_create import TransactionCreate

class TestTransactionCreate(unittest.TestCase):
    """TransactionCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionCreate:
        """Test TransactionCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionCreate`
        """
        model = TransactionCreate()
        if include_optional:
            return TransactionCreate(
                description = '012',
                amount = 0.0,
                transaction_type = 'expense',
                category = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TransactionCreate(
                description = '012',
                amount = 0.0,
                transaction_type = 'expense',
        )
        """

    def testTransactionCreate(self):
        """Test TransactionCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
