# coding: utf-8

"""
    Personal Finance Tracker

    Personal Finance Tracker API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finance_sdk.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_batch_reclassify_transactions_batch_reclassify_patch(self) -> None:
        """Test case for batch_reclassify_transactions_batch_reclassify_patch

        Batch Reclassify
        """
        pass

    def test_bulk_import_transactions_transactions_batch_import_post(self) -> None:
        """Test case for bulk_import_transactions_transactions_batch_import_post

        Bulk Import Transactions
        """
        pass

    def test_create_transaction_transactions_post(self) -> None:
        """Test case for create_transaction_transactions_post

        Create Transaction
        """
        pass

    def test_delete_transaction_transactions_transaction_id_delete(self) -> None:
        """Test case for delete_transaction_transactions_transaction_id_delete

        Delete Transaction
        """
        pass

    def test_get_financial_insights_transactions_analytics_insights_get(self) -> None:
        """Test case for get_financial_insights_transactions_analytics_insights_get

        Get Financial Insights
        """
        pass

    def test_get_summary_transactions_summary_get(self) -> None:
        """Test case for get_summary_transactions_summary_get

        Get Summary
        """
        pass

    def test_list_transactions_transactions_get(self) -> None:
        """Test case for list_transactions_transactions_get

        List Transactions
        """
        pass

    def test_reclassify_transaction_transactions_transaction_id_reclassify_patch(self) -> None:
        """Test case for reclassify_transaction_transactions_transaction_id_reclassify_patch

        Reclassify Transaction
        """
        pass

    def test_suggest_category_transactions_suggest_category_post(self) -> None:
        """Test case for suggest_category_transactions_suggest_category_post

        Suggest Category
        """
        pass

    def test_update_transaction_status_transactions_transaction_id_status_patch(self) -> None:
        """Test case for update_transaction_status_transactions_transaction_id_status_patch

        Update Transaction Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
