# coding: utf-8

"""
    Personal Finance Tracker

    Personal Finance Tracker API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from finance_sdk.models.suggest_category_request import SuggestCategoryRequest

class TestSuggestCategoryRequest(unittest.TestCase):
    """SuggestCategoryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuggestCategoryRequest:
        """Test SuggestCategoryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuggestCategoryRequest`
        """
        model = SuggestCategoryRequest()
        if include_optional:
            return SuggestCategoryRequest(
                description = '012'
            )
        else:
            return SuggestCategoryRequest(
                description = '012',
        )
        """

    def testSuggestCategoryRequest(self):
        """Test SuggestCategoryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
